#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server

m="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $4 ]; then
	scp -i $4 -o $1 $3@$2:~
else
	echo "$m";
fi
