#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
