#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y haproxy
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 531337-web-01 52.201.160.255:80 check\n\tserver 531337-web-02 100.25.102.0:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
